---
- name: Provision EC2 instance
  hosts: localhost
  vars:
      region:   eu-west-1
      ami:      ami-7b2ce20c
      set_dns:  False
      instance: t1.micro
  connection: local
  gather_facts: false
  tasks:
    - name: Launch instance
      ec2:
        keypair={{ keypair }}
        instance_type={{ instance }}
        image={{ ami }}
        region={{ region }}
        wait=yes
      register: ec2

    - name: Add new instance to host group
      local_action: add_host hostname={{ item.public_dns_name }}
                    groupname=launched
      with_items: ec2.instances

    - name: Ensure DNS entry exists
      route53: command=create overwrite=yes
               record=ci.{{ dns_zone }} type=A zone={{ dns_zone }}
               value={{ item.public_ip }}
      with_items: ec2.instances
      when: set_dns

    - name: Wait for SSH to come up
      local_action: wait_for host={{ item.public_dns_name }}
                    port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- include: jenkins.yaml
